/**
 * @file src/apps/finance/navigation.js
 * @description Navigation contribution for the finance app.
 */

export default [
  {
    id: 'finance-dashboard',
    label: 'Finance',
    to: '/finance',
    icon: 'Landmark',
    order: 40,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-transactions',
    label: 'Transactions',
    to: '/finance/transactions',
    icon: 'ReceiptText',
    order: 41,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-payments',
    label: 'Payments',
    to: '/finance/payments',
    icon: 'WalletCards',
    order: 42,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-invoices',
    label: 'Invoices',
    to: '/finance/invoices',
    icon: 'FileText',
    order: 43,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-receivables',
    label: 'Receivables',
    to: '/finance/receivables',
    icon: 'BadgeDollarSign',
    order: 44,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-audit',
    label: 'Audit',
    to: '/finance/audit',
    icon: 'ShieldCheck',
    order: 49,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-refunds',
    label: 'Refunds',
    to: '/finance/refunds',
    icon: 'Undo2',
    order: 43,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-expenses',
    label: 'Expenses',
    to: '/finance/expenses',
    icon: 'BadgeDollarSign',
    order: 44,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-payouts',
    label: 'Consultant Payouts',
    to: '/finance/payouts',
    icon: 'HandCoins',
    order: 45,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-my-payouts',
    label: 'My Payouts',
    to: '/finance/my-payouts',
    icon: 'HandCoins',
    order: 46,
    roles: ['consultant'],
  },
  {
    id: 'finance-accounts',
    label: 'Accounts',
    to: '/finance/accounts',
    icon: 'BookOpenText',
    order: 47,
    roles: ['admin', 'receptionist'],
  },
  {
    id: 'finance-reports',
    label: 'Reports',
    to: '/finance/reports',
    icon: 'ChartNoAxesColumn',
    order: 48,
    roles: ['admin', 'receptionist'],
  },
]
